spring:
    application:
        name: ch01

logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%t] %highlight(%p) %C(Line:%L) - %m%n"  # 控制台日志的输出格式
        file: "%d{yyyy-MM-dd HH:mm:ss} [%t] %p %C(Line:%L) - %m%n"                 # 文件日志的输出格式
    level:
        root: info                                                                 # 输出级别
    file:
        name: logs/testLog.log                                                      # 文件日志的存放地址与文件名
    logback:
        rollingpolicy:
            max-file-size: 1KB                                                        # 单个文件日志最大大小
            max-history: 7                                                            # 最大保留的历史文件日志数量
