spring:
  rabbitmq:
    # \u4E3B\u673A\u5730\u5740
    addresses: 127.0.0.1
    # \u8FDE\u63A5\u7AEF\u53E3
    port: 5672
    # \u8D26\u53F7\u5BC6\u7801,\u9ED8\u8BA4guest
    username: wangl
    password: wangl
    # \u865A\u62DF\u4E3B\u673A\u5730\u5740\uFF0C\u9ED8\u8BA4"/"
    virtual-host: /
    # \u8FDE\u63A5\u7684\u8D85\u65F6\u65F6\u95F4
    connection-timeout: 5000
    # \u76D1\u542C\u5BB9\u5668\u7684\u914D\u7F6E\uFF08\u6D88\u8D39\u8005\u914D\u7F6E\uFF09
    listener:
      # \u7B80\u5355\u7684\u76D1\u542C\u5BB9\u5668\u914D\u7F6E,\u57FA\u672C\u4E0A\u6EE1\u8DB3\u5927\u90E8\u5206\u7684\u9700\u6C42
      simple:
        # \u6700\u5C0F\u7684\u6D88\u8D39\u7EBF\u7A0B\u6570\uFF0C\u8FD9\u91CC\u8868\u793A\u6BCF\u4E2A\u76D1\u542C\u5BB9\u5668\u5C06\u5F00\u542F2\u4E2A\u7EBF\u7A0B\u53BB\u5904\u7406\u6D88\u606F
        concurrency: 2
        # \u6700\u5927\u7684\u6D88\u8D39\u7EBF\u7A0B\u6570
        max-concurrency: 10
        # \u6BCF\u4E2A\u7EBF\u7A0B\u80FD\u4ECE\u81EA\u8EAB\u7684\u961F\u5217\u4E2D\u6293\u53D6\u591A\u5C11\u6761\u6D88\u606F\uFF08\u4E0D\u5EFA\u8BAE\u8BBE\u7F6E\u8FC7\u5927\uFF0C\u9632\u6B62\u7EBF\u7A0B\u503E\u659C\uFF09
        prefetch: 1
        # \u6D88\u8D39\u8005\u7684\u7B7E\u6536\u6A21\u5F0F
        # none: \u8868\u793A\u6CA1\u6709\u4EFB\u4F55\u7684\u5E94\u7B54
        # auto: \u8868\u793A\u81EA\u52A8\u5E94\u7B54\uFF0C\u9664\u975E\u76D1\u542C\u5668\u629B\u51FA\u5F02\u5E38\uFF0C\u5E94\u7B54\u4F1A\u5931\u8D25\uFF08\u9ED8\u8BA4\u8BBE\u7F6E\uFF09
        # manual: \u8868\u793A\u624B\u52A8\u7B7E\u6536\uFF0C\u5FC5\u987B\u8C03\u7528\u76F8\u5E94\u7684ack\u65B9\u6CD5\u624D\u4F1A\u6267\u884C\u5E94\u7B54
        acknowledge-mode: manual
        # \u5F53\u6D88\u8D39\u8005\u76D1\u542C\u5668\u4EA7\u751F\u5F02\u5E38\u65F6\u662F\u5426\u5C06\u6D88\u606F\u91CD\u65B0\u653E\u56DE\u961F\u5217\uFF08\u9ED8\u8BA4\u503Ctrue\uFF09
        default-requeue-rejected: true


