spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/java211?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: root
        # 指定连接类型
#        type: com.alibaba.druid.pool.DruidDataSource
        # druid连接池
        druid:
            # 最大连接数
            max-active: 200
            # 最小空闲连接数
            min-idle: 5
            # 初始化连接数
            initial-size: 5
            # 极限空闲时长1
            max-wait: 5000
            # 检查连接是否有效
            validation-query: select 1
            # 是否缓存PreparedStatement
            pool-prepared-statements: false



#        # SB自带的连接池（Hikari）
#        hikari:
#            # 最小空闲连接数
#            minimum-idle: 5
#            # 最大连接数
#            maximum-pool-size: 200
#            # 极限空闲时长（超出后将大于最小空闲连接数量的连接关掉）
#            idle-timeout: 90000
#            # 超时时长（超出后还没从池子里拿到连接就报错）
#            connection-timeout: 5000
#            # 检查连接是否有效
#            connection-test-query: select 1