spring:
    application:
        name: ch07
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/java211?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: root
        c3p0:
            max-pool-size: 100
            min-pool-size: 10
            initial-pool-size: 5
            max-idle-time: 3000
        type: com.mchange.v2.c3p0.ComboPooledDataSource


