spring:
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: wangl
    password: wangl
    virtual-host: /
    connection-timeout: 5000
    # \u65B9\u5F0F\u4E00\uFF1A\u542F\u7528ConfirmCallback\u6A21\u5F0F\uFF0C\u8FD9\u79CD\u6A21\u5F0F\u7528\u4E8E\u786E\u8BA4\u6D88\u606F\u6295\u9012\u5230\u4EA4\u6362\u673A
    # publisher-confirm-type: correlated
    # \u65B9\u5F0F\u4E8C\uFF1A\u542F\u7528ReturnsCallback\u6A21\u5F0F\uFF0C\u8FD9\u79CD\u6A21\u5F0F\u7528\u4E8E\u786E\u8BA4\u6D88\u606F\u6B63\u786E\u8DEF\u7531\u5230\u961F\u5217\u4E2D
    publisher-returns: true
    template:
      # \u5F53mandatory\u8BBE\u7F6E\u4E3Atrue\u65F6\uFF0C\u5982\u679C\u4EA4\u6362\u673A\u6839\u636E\u8DEF\u7531\u7684key\u65E0\u6CD5\u627E\u5230\u4E00\u4E2A\u5408\u9002\u7684\u961F\u5217\u65F6\uFF0C
      # \u90A3\u4E48rabbitmq\u4F1A\u5C06\u6D88\u606F\u8FD4\u56DE\u7ED9\u751F\u4EA7\u8005\u3002\u5982\u679C\u8BBE\u7F6E\u4E3Afalse\uFF0C\u5219\u51FA\u73B0\u4E0A\u8FF0\u7684\u60C5\u51B5\u65F6\u4F1A\u76F4\u63A5
      # \u5C06\u6D88\u606F\u4E22\u5F03
      mandatory: true

