spring:
    application:
        name: ch13_homework
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/fuckinghomework?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: root
        hikari:
            # ???????
            minimum-idle: 5
            # ?????
            maximum-pool-size: 200
            # ???????????????????????????
            idle-timeout: 90000
            # ??????????????????????
            connection-timeout: 5000
            # ????????
            connection-test-query: select 1

    data:
        redis:
            # ??????0-15?
            database: 0
            # ????
            host: 127.0.0.1
            # ???
            port: 6379
            # ?????????
            # password: 123456
            # ??????
            timeout: 2000
            # ??????
            connect-timeout: 2000
    rabbitmq:
        addresses: 127.0.0.1
        port: 5672
        username: guest
        password: guest
        virtual-host: /
        connection-timeout: 3000
        # \u6D88\u8D39\u7AEF\u7684\u76D1\u542C\u5668\u914D\u7F6E
        listener:
            simple:
                concurrency: 1
                max-concurrency: 5
                prefetch: 1
                # \u81EA\u52A8\u7B7E\u6536(\u6CE8\u610F\uFF1A\u53EA\u6709auto\u6A21\u5F0F\u9002\u5408retry\u6A21\u5757\u5B9E\u73B0\u91CD\u8BD5\u5E76\u81EA\u52A8\u6295\u9012\u5230\u6B7B\u4FE1\u4EA4\u6362\u673A)
                # \u5982\u679C\u662F\u624B\u52A8\u7B7E\u6536\uFF0C\u5EFA\u8BAE\u7ED3\u5408redis\u81EA\u884C\u5B9E\u73B0\u91CD\u8BD5\u673A\u5236\u548C\u6D88\u606F\u7684\u6295\u9012
                acknowledge-mode: auto
                # \u6D88\u8D39\u91CD\u8BD5\u8BBE\u7F6E
                retry:
                    enabled: true
                    max-attempts: 3
                    initial-interval: 2000ms
    elasticsearch:
        # ??es??????????????????
        uris: http://localhost:9200
        # ??????
        connection-timeout: 2s
        # ????????????
        # username: xxx
        # password: xxx

mybatis:
    # ??????
    type-aliases-package: com.example.ch13_homework.entity
    # mapper????
    mapper-locations: classpath:mappers/*.xml
    configuration:
        # ????
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl