spring:
  rabbitmq:
    # 主机地址
    addresses: 127.0.0.1
    # 连接端口
    port: 5672
    # 账号密码,默认guest
    username: wangl
    password: wangl
    # 虚拟主机地址，默认"/"
    virtual-host: /
    # 连接的超时时间
    connection-timeout: 5000
    # 监听容器的配置（消费者配置）
    listener:
      # 简单的监听容器配置,基本上满足大部分的需求
      simple:
        # 最小的消费线程数，这里表示每个监听容器将开启2个线程去处理消息
        concurrency: 2
        # 最大的消费线程数
        max-concurrency: 10
        # 每个线程能从自身的队列中抓取多少条消息（不建议设置过大，防止线程倾斜）
        prefetch: 1
        # 消费者的签收模式
        # none: 表示没有任何的应答
        # auto: 表示自动应答，除非监听器抛出异常，应答会失败（默认设置）
        # manual: 表示手动签收，必须调用相应的ack方法才会执行应答
        acknowledge-mode: auto
        # 当消费者监听器产生异常时是否将消息重新放回队列（默认值true）
        default-requeue-rejected: true
        # 设置重试机制（基于spring-retry模块来实现）
        retry:
          # 启用重试机制
          enabled: true
          # 重试次数
          max-attempts: 3
          # 重试间隔时间
          initial-interval: 2000ms


